<a href="https://colab.research.google.com/github/HaEunMok/ML/blob/main/%5Btensorflow%5D_basic_tensorflow_(for_beginner).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Keras를 사용하여 기본 사용법 익히기
https://www.tensorflow.org/tutorials/quickstart/beginner?hl=ko


## 1. tensorflow import하기

In [14]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


## 2. 데이터 세트 로드하기**

keras의 MNIST 데이터셋을 로드하기

애초에 훈련데이터와 테스트데이터가 나눠져 있음



In [15]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

## 3. 신경망 훈련하기

layer를 쌓아 시퀀스 모델을 생성

훈련에 사용할 옵티마이저와 손실함수 선택



In [16]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [17]:
# 에측하기
predictions = model(x_train[:1]).numpy()
predictions

array([[0.07619509, 0.06328992, 0.05360058, 0.08566909, 0.10235608,
        0.09802897, 0.12770545, 0.11783875, 0.1429249 , 0.13239117]],
      dtype=float32)

In [18]:
# 활성화함수 사용 (softmax)
tf.nn.softmax(predictions).numpy()

array([[0.09760735, 0.0963558 , 0.09542668, 0.09853648, 0.10019454,
        0.09976193, 0.10276688, 0.1017579 , 0.1043429 , 0.10324955]],
      dtype=float32)

In [19]:
# 손실 함수(loss function) : 로짓을 통해 손실 계산
# fron_logits=True시, 활성화함수 전 값을 얻을 수 있음
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [20]:
loss_fn(y_train[:1], predictions).numpy()

2.3049686

In [21]:
# loss 를 설정하여 모델 생성
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

## 4. 모델 정확도 평가하기


In [22]:
# 모델을 훈련하기
# epoch : 데이터 학습과정 횟수. 과적합과 관련 있음.
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2987 - accuracy: 0.9129
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1420 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1069 - accuracy: 0.9687
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0874 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0739 - accuracy: 0.9767


In [23]:
# 모델 평가하기
# verbose : 얼마나 상세하게 정보를 출력할 것인가 (0 또는 False: 아무런 출력이 없음. 1 또는 True: 기본 출력 레벨. 2 이상: 상세한 출력이나 디버깅 메시지를 표시할 때 사용.)
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0735 - accuracy: 0.9780 - 580ms/epoch - 2ms/step


[0.0735381618142128, 0.9779999852180481]

In [24]:
# 확률을 반환하도록 모델 래핑
# 래핑 : 모델을 다른 프레임워크, 라이브러리, 인터페이스를 적용하기 위해 감싸는 것을 의미
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [25]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533858, 0.08533853, 0.08533878, 0.08534853, 0.08533853,
        0.08533857, 0.08533853, 0.23194094, 0.08533855, 0.08534042],
       [0.08533872, 0.08535176, 0.2319381 , 0.08533874, 0.08533872,
        0.08533908, 0.08533873, 0.08533872, 0.08533872, 0.08533872],
       [0.08534087, 0.23190399, 0.08534258, 0.08534113, 0.08534357,
        0.08534094, 0.08534098, 0.08535941, 0.08534558, 0.08534095],
       [0.23184197, 0.08534489, 0.08535141, 0.08534483, 0.0853452 ,
        0.08534823, 0.08535456, 0.08537675, 0.08534479, 0.08534739],
       [0.08537229, 0.08537227, 0.08537335, 0.08537228, 0.23140635,
        0.0853723 , 0.08537244, 0.0853859 , 0.08537243, 0.08560047]],
      dtype=float32)>