<a href="https://colab.research.google.com/github/HaEunMok/ML/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Keras를 사용하여 기본 사용법 익히기
https://www.tensorflow.org/tutorials/quickstart/beginner?hl=ko


## 1. tensorflow import하기

In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


## 2. 데이터 세트 로드하기**

keras의 MNIST 데이터셋을 로드하기

애초에 훈련데이터와 테스트데이터가 나눠져 있음



In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


## 3. 신경망 훈련하기

layer를 쌓아 시퀀스 모델을 생성

훈련에 사용할 옵티마이저와 손실함수 선택



In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [4]:
# 에측하기
predictions = model(x_train[:1]).numpy()
predictions

array([[0.12030686, 0.13140069, 0.05216905, 0.08795399, 0.10684036,
        0.05816129, 0.08109786, 0.06175974, 0.1850274 , 0.11528277]],
      dtype=float32)

In [5]:
# 활성화함수 사용 (softmax)
tf.nn.softmax(predictions).numpy()

array([[0.1019747 , 0.10311229, 0.0952578 , 0.09872832, 0.10061067,
        0.09583033, 0.09805375, 0.09617578, 0.10879281, 0.10146365]],
      dtype=float32)

In [6]:
# 손실 함수(loss function) : 로짓을 통해 손실 계산
# fron_logits=True시, 활성화함수 전 값을 얻을 수 있음
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.3451762

In [8]:
# loss 를 설정하여 모델 생성
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

## 4. 모델 정확도 평가하기


In [9]:
# 모델을 훈련하기
# epoch : 데이터 학습과정 횟수. 과적합과 관련 있음.
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


/usr/local/lib/python3.10/dist-packages/keras/src/backend.py:5727: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


1875/1875 [==============================] - 14s 7ms/step - loss: 0.2937 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1406 - accuracy: 0.9578
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1055 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0874 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0760 - accuracy: 0.9761


In [11]:
# 모델 평가하기
# verbose : 얼마나 상세하게 정보를 출력할 것인가 (0 또는 False: 아무런 출력이 없음. 1 또는 True: 기본 출력 레벨. 2 이상: 상세한 출력이나 디버깅 메시지를 표시할 때 사용.)
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0723 - accuracy: 0.9775 - 648ms/epoch - 2ms/step


[0.07231270521879196, 0.9775000214576721]

In [12]:
# 확률을 반환하도록 모델 래핑
# 래핑 : 모델을 다른 프레임워크, 라이브러리, 인터페이스를 적용하기 위해 감싸는 것을 의미
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533783, 0.08533777, 0.08533895, 0.08534288, 0.08533777,
        0.08533777, 0.08533777, 0.231953  , 0.08533783, 0.08533837],
       [0.08533736, 0.08534119, 0.23195946, 0.08533744, 0.08533736,
        0.08533754, 0.08533737, 0.08533736, 0.08533749, 0.08533736],
       [0.0853425 , 0.23187816, 0.0853475 , 0.08534269, 0.08534341,
        0.08534279, 0.08534284, 0.08536966, 0.08534786, 0.08534256],
       [0.23193884, 0.08533867, 0.08534344, 0.08533886, 0.08533868,
        0.08533891, 0.08534095, 0.08534335, 0.08533868, 0.08533958],
       [0.0854925 , 0.08549218, 0.08549224, 0.08549218, 0.22948913,
        0.08549222, 0.08549397, 0.08549964, 0.08549225, 0.08656362]],
      dtype=float32)>